version: "3.9"

services:
  flomepage:
    image: ozeliurs/flomepage:latest
    restart: unless-stopped
    container_name: flomepage
    env_file:
      - .flomepage.env
    volumes:
      - ./flomepage:/app/persistent
      - ./i2l:/app/IP2LOCATION
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flomepage.rule=Host(`flomepage.${BASE_DOMAIN:-ozeliurs.com}`)"
      - "traefik.http.routers.flomepage.entrypoints=websecure"
      - "traefik.http.routers.flomepage.tls=true"
      - "traefik.http.routers.flomepage.tls.certresolver=cloudflare"

      - "com.centurylinklabs.watchtower.enable=true"
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:5000" ]

  ozeliurs-com:
    image: ozeliurs/ozeliurs-com:latest
    container_name: ozeliurs-com
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.beta-ozeliurs.rule=Host(`${BASE_DOMAIN:-ozeliurs.com}`) || Host(`www.${BASE_DOMAIN:-ozeliurs.com}`)"
      - "traefik.http.routers.beta-ozeliurs.entrypoints=websecure"
      - "traefik.http.routers.beta-ozeliurs.tls=true"
      - "traefik.http.routers.beta-ozeliurs.tls.certresolver=cloudflare"

      - "com.centurylinklabs.watchtower.enable=true"
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:5000" ]

networks:
  traefik:
    external: true